package cn.saymagic.begonia.util

object Constants {

    val PHOTO_ID = "PHOTO_ID"
    val USER_NAME = "USER_NAME"

    val PHOTO_DATA_TYPE_NORMAL = "PHOTO_DATA_TYPE_NORMAL"

    val PHOTO_DATA_TYPE_USER = "PHOTO_DATA_TYPE_USER"

    val PHOTO_DATA_TYPE_USER_LIKED = "PHOTO_DATA_TYPE_USER_LIKED"
    val PHOTO_DATA_TYPE_COLLECTION = "PHOTO_DATA_TYPE_COLLECTION"

    val PHOTO_DATA_TYPE_SEARCH = "PHOTO_DATA_TYPE_SEARCH"

    val PHOTO_DATA_PARAM_USERNAME = "PHOTO_DATA_PARAM_USERNAME"
    val PHOTO_DATA_PARAM_SEARCH_TEXT = "PHOTO_DATA_PARAM_SEARCH_TEXT"

    val PHOTO_DATA_PARAM_COLLECTION_ID= "PHOTO_DATA_PARAM_COLLECTION_ID"

    val COLLECTION_DATA_TYPE_USER = "COLLECTION_DATA_TYPE_USER"

    val COLLECTION_DATA_PARAM_USERNAME = "COLLECTION_DATA_PARAM_USERNAME"

    val COLLECTION_DATA_TYPE_SEARCH = "COLLECTION_DATA_TYPE_SEARCH"
    val COLLECTION_DATA_PARAM_SEARCH_TEXT = "COLLECTION_DATA_PARAM_SEARCH_TEXT"

    val USER_DATA_TYPE_SEARCH = "USER_DATA_TYPE_SEARCH"

    val USER_DATA_TYPE_PARAM_SEARCH_TEXT = "USER_DATA_TYPE_PARAM_SEARCH_TEXT"


}